# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'seeder_ui_v03.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import os

class Ui_SEMEA(object):
    def setupUi(self, SEMEA):
        SEMEA.setObjectName("SEMEA")
        SEMEA.resize(800, 430)
        icon = QtGui.QIcon()
        self.dir=os.path.dirname(os.path.abspath(__file__)) 
        icon.addPixmap(QtGui.QPixmap(os.path.join(self.dir,"icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SEMEA.setWindowIcon(icon)
        SEMEA.setTabPosition(QtWidgets.QTabWidget.North)
        self.main = QtWidgets.QWidget()
        self.main.setObjectName("main")
        self.vel_3 = QtWidgets.QComboBox(self.main)
        self.vel_3.setGeometry(QtCore.QRect(910, 120, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.vel_3.setFont(font)
        self.vel_3.setObjectName("vel_3")
        self.vel_3.addItem("")
        self.vel_3.addItem("")
        self.vel_3.addItem("")
        self.vel_3.addItem("")
        self.gv = QtWidgets.QGraphicsView(self.main)
        self.gv.setGeometry(QtCore.QRect(10, 10, 491, 291))
        self.gv.setObjectName("gv")
        self.layoutWidget_2 = QtWidgets.QWidget(self.main)
        self.layoutWidget_2.setGeometry(QtCore.QRect(518, 10, 261, 351))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_14 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_2.addWidget(self.label_14)
        self.ql_speed = QtWidgets.QPlainTextEdit(self.layoutWidget_2)
        self.ql_speed.setMaximumSize(QtCore.QSize(80, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ql_speed.setFont(font)
        self.ql_speed.setObjectName("ql_speed")
        self.horizontalLayout_2.addWidget(self.ql_speed)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_11 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_3.addWidget(self.label_11)
        self.ql_pdop = QtWidgets.QPlainTextEdit(self.layoutWidget_2)
        self.ql_pdop.setMaximumSize(QtCore.QSize(80, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ql_pdop.setFont(font)
        self.ql_pdop.setObjectName("ql_pdop")
        self.horizontalLayout_3.addWidget(self.ql_pdop)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_28 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_4.addWidget(self.label_28)
        self.ql_seed = QtWidgets.QPlainTextEdit(self.layoutWidget_2)
        self.ql_seed.setMaximumSize(QtCore.QSize(80, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ql_seed.setFont(font)
        self.ql_seed.setObjectName("ql_seed")
        self.horizontalLayout_4.addWidget(self.ql_seed)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_29 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_5.addWidget(self.label_29)
        self.ql_fert_rt = QtWidgets.QPlainTextEdit(self.layoutWidget_2)
        self.ql_fert_rt.setMaximumSize(QtCore.QSize(80, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ql_fert_rt.setFont(font)
        self.ql_fert_rt.setObjectName("ql_fert_rt")
        self.horizontalLayout_5.addWidget(self.ql_fert_rt)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_31 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_7.addWidget(self.label_31)
        self.ql_fert_wgt = QtWidgets.QPlainTextEdit(self.layoutWidget_2)
        self.ql_fert_wgt.setMaximumSize(QtCore.QSize(80, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ql_fert_wgt.setFont(font)
        self.ql_fert_wgt.setObjectName("ql_fert_wgt")
        self.horizontalLayout_7.addWidget(self.ql_fert_wgt)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_32 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_8.addWidget(self.label_32)
        self.ql_area = QtWidgets.QPlainTextEdit(self.layoutWidget_2)
        self.ql_area.setMaximumSize(QtCore.QSize(80, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ql_area.setFont(font)
        self.ql_area.setObjectName("ql_area")
        self.horizontalLayout_8.addWidget(self.ql_area)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_34 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.horizontalLayout_9.addWidget(self.label_34)
        self.ql_opcap = QtWidgets.QPlainTextEdit(self.layoutWidget_2)
        self.ql_opcap.setMaximumSize(QtCore.QSize(80, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ql_opcap.setFont(font)
        self.ql_opcap.setObjectName("ql_opcap")
        self.horizontalLayout_9.addWidget(self.ql_opcap)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.exit = QtWidgets.QPushButton(self.main)
        self.exit.setGeometry(QtCore.QRect(20, 310, 120, 81))
        self.exit.setMinimumSize(QtCore.QSize(0, 75))
        self.exit.setMaximumSize(QtCore.QSize(120, 90))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.exit.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(os.path.join(self.dir,"exit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exit.setIcon(icon1)
        self.exit.setIconSize(QtCore.QSize(64, 54))
        self.exit.setObjectName("exit")
        self.bt_to_conf = QtWidgets.QPushButton(self.main)
        self.bt_to_conf.setGeometry(QtCore.QRect(150, 310, 120, 80))
        self.bt_to_conf.setMinimumSize(QtCore.QSize(120, 80))
        self.bt_to_conf.setMaximumSize(QtCore.QSize(120, 80))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.bt_to_conf.setFont(font)
        self.bt_to_conf.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(os.path.join(self.dir,"go.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_to_conf.setIcon(icon2)
        self.bt_to_conf.setIconSize(QtCore.QSize(64, 64))
        self.bt_to_conf.setObjectName("bt_to_conf")
        self.lb_status = QtWidgets.QLabel(self.main)
        self.lb_status.setGeometry(QtCore.QRect(290, 370, 481, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lb_status.setFont(font)
        self.lb_status.setObjectName("lb_status")
        self.exit.raise_()
        self.bt_to_conf.raise_()
        self.vel_3.raise_()
        self.gv.raise_()
        self.layoutWidget_2.raise_()
        self.lb_status.raise_()
        SEMEA.addTab(self.main, "")
        self.config = QtWidgets.QWidget()
        self.config.setObjectName("config")
        self.line_3 = QtWidgets.QFrame(self.config)
        self.line_3.setGeometry(QtCore.QRect(20, 250, 751, 21))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.bt_back_main = QtWidgets.QPushButton(self.config)
        self.bt_back_main.setGeometry(QtCore.QRect(521, 281, 120, 80))
        self.bt_back_main.setMinimumSize(QtCore.QSize(120, 80))
        self.bt_back_main.setMaximumSize(QtCore.QSize(120, 80))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.bt_back_main.setFont(font)
        self.bt_back_main.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(os.path.join(self.dir,"back.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)

        self.bt_back_main.setIcon(icon3)
        self.bt_back_main.setIconSize(QtCore.QSize(64, 64))
        self.bt_back_main.setObjectName("bt_back_main")
        self.bt_to_aux = QtWidgets.QPushButton(self.config)
        self.bt_to_aux.setGeometry(QtCore.QRect(640, 280, 120, 80))
        self.bt_to_aux.setMinimumSize(QtCore.QSize(120, 80))
        self.bt_to_aux.setMaximumSize(QtCore.QSize(120, 80))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.bt_to_aux.setFont(font)
        self.bt_to_aux.setText("")
        self.bt_to_aux.setIcon(icon2)
        self.bt_to_aux.setIconSize(QtCore.QSize(64, 64))
        self.bt_to_aux.setObjectName("bt_to_aux")
        self.layoutWidget_7 = QtWidgets.QWidget(self.config)
        self.layoutWidget_7.setGeometry(QtCore.QRect(20, 300, 481, 41))
        self.layoutWidget_7.setObjectName("layoutWidget_7")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.layoutWidget_7)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_23 = QtWidgets.QLabel(self.layoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_13.addWidget(self.label_23)
        self.m_pop_7 = QtWidgets.QPushButton(self.layoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.m_pop_7.setFont(font)
        self.m_pop_7.setObjectName("m_pop_7")
        self.horizontalLayout_13.addWidget(self.m_pop_7)
        self.ql_row_spacing = QtWidgets.QPlainTextEdit(self.layoutWidget_7)
        self.ql_row_spacing.setMaximumSize(QtCore.QSize(80, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ql_row_spacing.setFont(font)
        self.ql_row_spacing.setObjectName("ql_row_spacing")
        self.horizontalLayout_13.addWidget(self.ql_row_spacing)
        self.m_pop_8 = QtWidgets.QPushButton(self.layoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.m_pop_8.setFont(font)
        self.m_pop_8.setObjectName("m_pop_8")
        self.horizontalLayout_13.addWidget(self.m_pop_8)
        self.widget = QtWidgets.QWidget(self.config)
        self.widget.setGeometry(QtCore.QRect(11, 120, 731, 41))
        self.widget.setObjectName("widget")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_20 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_12.addWidget(self.label_20)
        self.m_pop_5 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.m_pop_5.setFont(font)
        self.m_pop_5.setObjectName("m_pop_5")
        self.horizontalLayout_12.addWidget(self.m_pop_5)
        self.ql_germ = QtWidgets.QPlainTextEdit(self.widget)
        self.ql_germ.setMaximumSize(QtCore.QSize(80, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ql_germ.setFont(font)
        self.ql_germ.setObjectName("ql_germ")
        self.horizontalLayout_12.addWidget(self.ql_germ)
        self.m_pop_6 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.m_pop_6.setFont(font)
        self.m_pop_6.setObjectName("m_pop_6")
        self.horizontalLayout_12.addWidget(self.m_pop_6)
        self.label_15 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_12.addWidget(self.label_15)
        self.list_holes = QtWidgets.QComboBox(self.widget)
        self.list_holes.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.list_holes.setFont(font)
        self.list_holes.setObjectName("list_holes")
        self.list_holes.addItem("")
        self.list_holes.addItem("")
        self.list_holes.addItem("")
        self.list_holes.addItem("")
        self.horizontalLayout_12.addWidget(self.list_holes)
        self.line = QtWidgets.QFrame(self.config)
        self.line.setGeometry(QtCore.QRect(11, 90, 759, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.config)
        self.line_2.setGeometry(QtCore.QRect(11, 168, 759, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.widget1 = QtWidgets.QWidget(self.config)
        self.widget1.setGeometry(QtCore.QRect(11, 200, 741, 42))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_38 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_38.setFont(font)
        self.label_38.setObjectName("label_38")
        self.horizontalLayout_14.addWidget(self.label_38)
        self.list_fert = QtWidgets.QComboBox(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.list_fert.setFont(font)
        self.list_fert.setObjectName("list_fert")
        self.list_fert.addItem("")
        self.list_fert.addItem("")
        self.list_fert.addItem("")
        self.horizontalLayout_14.addWidget(self.list_fert)
        self.bt_load_fert = QtWidgets.QPushButton(self.widget1)
        self.bt_load_fert.setMinimumSize(QtCore.QSize(0, 40))
        self.bt_load_fert.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.bt_load_fert.setFont(font)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(os.path.join(self.dir,"file.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_load_fert.setIcon(icon4)
        self.bt_load_fert.setIconSize(QtCore.QSize(32, 32))
        self.bt_load_fert.setObjectName("bt_load_fert")
        self.horizontalLayout_14.addWidget(self.bt_load_fert)
        self.m_pop_3 = QtWidgets.QPushButton(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.m_pop_3.setFont(font)
        self.m_pop_3.setObjectName("m_pop_3")
        self.horizontalLayout_14.addWidget(self.m_pop_3)
        self.label_25 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_14.addWidget(self.label_25)
        self.ql_set_fert = QtWidgets.QPlainTextEdit(self.widget1)
        self.ql_set_fert.setMaximumSize(QtCore.QSize(80, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ql_set_fert.setFont(font)
        self.ql_set_fert.setObjectName("ql_set_fert")
        self.horizontalLayout_14.addWidget(self.ql_set_fert)
        self.m_pop_4 = QtWidgets.QPushButton(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.m_pop_4.setFont(font)
        self.m_pop_4.setObjectName("m_pop_4")
        self.horizontalLayout_14.addWidget(self.m_pop_4)
        self.widget2 = QtWidgets.QWidget(self.config)
        self.widget2.setGeometry(QtCore.QRect(12, 22, 721, 42))
        self.widget2.setObjectName("widget2")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.widget2)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_36 = QtWidgets.QLabel(self.widget2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_36.setFont(font)
        self.label_36.setObjectName("label_36")
        self.horizontalLayout_11.addWidget(self.label_36)
        self.list_seed = QtWidgets.QComboBox(self.widget2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.list_seed.setFont(font)
        self.list_seed.setObjectName("list_seed")
        self.list_seed.addItem("")
        self.list_seed.addItem("")
        self.list_seed.addItem("")
        self.horizontalLayout_11.addWidget(self.list_seed)
        self.bt_load_seed = QtWidgets.QPushButton(self.widget2)
        self.bt_load_seed.setMinimumSize(QtCore.QSize(0, 40))
        self.bt_load_seed.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.bt_load_seed.setFont(font)
        self.bt_load_seed.setIcon(icon4)
        self.bt_load_seed.setIconSize(QtCore.QSize(32, 32))
        self.bt_load_seed.setObjectName("bt_load_seed")
        self.horizontalLayout_11.addWidget(self.bt_load_seed)
        self.m_pop = QtWidgets.QPushButton(self.widget2)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.m_pop.setFont(font)
        self.m_pop.setObjectName("m_pop")
        self.horizontalLayout_11.addWidget(self.m_pop)
        self.ql_set_pop = QtWidgets.QPlainTextEdit(self.widget2)
        self.ql_set_pop.setMaximumSize(QtCore.QSize(80, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ql_set_pop.setFont(font)
        self.ql_set_pop.setObjectName("ql_set_pop")
        self.horizontalLayout_11.addWidget(self.ql_set_pop)
        self.p_pop = QtWidgets.QPushButton(self.widget2)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.p_pop.setFont(font)
        self.p_pop.setObjectName("p_pop")
        self.horizontalLayout_11.addWidget(self.p_pop)
        self.label_21 = QtWidgets.QLabel(self.widget2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_11.addWidget(self.label_21)
        SEMEA.addTab(self.config, "")
        self.aux = QtWidgets.QWidget()
        self.aux.setObjectName("aux")
        self.bt_back_conf = QtWidgets.QPushButton(self.aux)
        self.bt_back_conf.setGeometry(QtCore.QRect(640, 280, 120, 80))
        self.bt_back_conf.setMinimumSize(QtCore.QSize(120, 80))
        self.bt_back_conf.setMaximumSize(QtCore.QSize(120, 80))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.bt_back_conf.setFont(font)
        self.bt_back_conf.setText("")
        self.bt_back_conf.setIcon(icon3)
        self.bt_back_conf.setIconSize(QtCore.QSize(64, 64))
        self.bt_back_conf.setObjectName("bt_back_conf")
        self.cb_motion_simulate = QtWidgets.QCheckBox(self.aux)
        self.cb_motion_simulate.setGeometry(QtCore.QRect(20, 240, 439, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cb_motion_simulate.setFont(font)
        self.cb_motion_simulate.setObjectName("cb_motion_simulate")
        self.layoutWidget_3 = QtWidgets.QWidget(self.aux)
        self.layoutWidget_3.setGeometry(QtCore.QRect(20, 59, 441, 34))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_39 = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_39.setFont(font)
        self.label_39.setObjectName("label_39")
        self.horizontalLayout_10.addWidget(self.label_39)
        self.list_com_port = QtWidgets.QComboBox(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.list_com_port.setFont(font)
        self.list_com_port.setObjectName("list_com_port")
        self.list_com_port.addItem("")
        self.list_com_port.addItem("")
        self.list_com_port.addItem("")
        self.horizontalLayout_10.addWidget(self.list_com_port)
        self.layoutWidget_4 = QtWidgets.QWidget(self.aux)
        self.layoutWidget_4.setGeometry(QtCore.QRect(20, 110, 441, 32))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget_4)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_40 = QtWidgets.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_40.setFont(font)
        self.label_40.setObjectName("label_40")
        self.horizontalLayout_6.addWidget(self.label_40)
        self.ql_logfile = QtWidgets.QPlainTextEdit(self.layoutWidget_4)
        self.ql_logfile.setMinimumSize(QtCore.QSize(250, 0))
        self.ql_logfile.setMaximumSize(QtCore.QSize(300, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ql_logfile.setFont(font)
        self.ql_logfile.setObjectName("ql_logfile")
        self.horizontalLayout_6.addWidget(self.ql_logfile)
        self.layoutWidget_5 = QtWidgets.QWidget(self.aux)
        self.layoutWidget_5.setGeometry(QtCore.QRect(21, 10, 441, 32))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.layoutWidget_5)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.cb_remote = QtWidgets.QCheckBox(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cb_remote.setFont(font)
        self.cb_remote.setObjectName("cb_remote")
        self.horizontalLayout_15.addWidget(self.cb_remote)
        self.ql_remote_status = QtWidgets.QPlainTextEdit(self.layoutWidget_5)
        self.ql_remote_status.setMinimumSize(QtCore.QSize(150, 0))
        self.ql_remote_status.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ql_remote_status.setFont(font)
        self.ql_remote_status.setObjectName("ql_remote_status")
        self.horizontalLayout_15.addWidget(self.ql_remote_status)
        self.layoutWidget_6 = QtWidgets.QWidget(self.aux)
        self.layoutWidget_6.setGeometry(QtCore.QRect(20, 159, 441, 52))
        self.layoutWidget_6.setObjectName("layoutWidget_6")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.layoutWidget_6)
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.bt_define_logfile = QtWidgets.QPushButton(self.layoutWidget_6)
        self.bt_define_logfile.setMinimumSize(QtCore.QSize(0, 50))
        self.bt_define_logfile.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.bt_define_logfile.setFont(font)
        self.bt_define_logfile.setIcon(icon4)
        self.bt_define_logfile.setIconSize(QtCore.QSize(32, 32))
        self.bt_define_logfile.setObjectName("bt_define_logfile")
        self.horizontalLayout_16.addWidget(self.bt_define_logfile)
        self.bt_reload_logfile = QtWidgets.QPushButton(self.layoutWidget_6)
        self.bt_reload_logfile.setMinimumSize(QtCore.QSize(0, 50))
        self.bt_reload_logfile.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.bt_reload_logfile.setFont(font)
        self.bt_reload_logfile.setIcon(icon4)
        self.bt_reload_logfile.setIconSize(QtCore.QSize(32, 32))
        self.bt_reload_logfile.setObjectName("bt_reload_logfile")
        self.horizontalLayout_16.addWidget(self.bt_reload_logfile)
        self.line_4 = QtWidgets.QFrame(self.aux)
        self.line_4.setGeometry(QtCore.QRect(20, 220, 451, 20))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.layoutWidget = QtWidgets.QWidget(self.aux)
        self.layoutWidget.setGeometry(QtCore.QRect(21, 271, 441, 41))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_22 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout.addWidget(self.label_22)
        self.m_pop_9 = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.m_pop_9.setFont(font)
        self.m_pop_9.setObjectName("m_pop_9")
        self.horizontalLayout.addWidget(self.m_pop_9)
        self.ql_sim_speed = QtWidgets.QPlainTextEdit(self.layoutWidget)
        self.ql_sim_speed.setMaximumSize(QtCore.QSize(80, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ql_sim_speed.setFont(font)
        self.ql_sim_speed.setObjectName("ql_sim_speed")
        self.horizontalLayout.addWidget(self.ql_sim_speed)
        self.m_pop_10 = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.m_pop_10.setFont(font)
        self.m_pop_10.setObjectName("m_pop_10")
        self.horizontalLayout.addWidget(self.m_pop_10)
        self.layoutWidget1 = QtWidgets.QWidget(self.aux)
        self.layoutWidget1.setGeometry(QtCore.QRect(520, 10, 251, 231))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.bt_tare = QtWidgets.QPushButton(self.layoutWidget1)
        self.bt_tare.setMinimumSize(QtCore.QSize(0, 50))
        self.bt_tare.setObjectName("bt_tare")
        self.verticalLayout_2.addWidget(self.bt_tare)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.lb_cal = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lb_cal.setFont(font)
        self.lb_cal.setObjectName("lb_cal")
        self.horizontalLayout_17.addWidget(self.lb_cal)
        self.bt_ok_cal = QtWidgets.QPushButton(self.layoutWidget1)
        self.bt_ok_cal.setMinimumSize(QtCore.QSize(0, 50))
        self.bt_ok_cal.setObjectName("bt_ok_cal")
        self.horizontalLayout_17.addWidget(self.bt_ok_cal)
        self.verticalLayout_2.addLayout(self.horizontalLayout_17)
        self.bt_calibrate = QtWidgets.QPushButton(self.layoutWidget1)
        self.bt_calibrate.setMinimumSize(QtCore.QSize(0, 50))
        self.bt_calibrate.setObjectName("bt_calibrate")
        self.verticalLayout_2.addWidget(self.bt_calibrate)
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.bt_back_conf.raise_()
        self.cb_motion_simulate.raise_()
        self.layoutWidget_3.raise_()
        self.layoutWidget_4.raise_()
        self.layoutWidget_5.raise_()
        self.layoutWidget_6.raise_()
        self.line_4.raise_()
        SEMEA.addTab(self.aux, "")

        self.retranslateUi(SEMEA)
        SEMEA.setCurrentIndex(0)
        
        self.bt_to_conf.clicked.connect(lambda:SEMEA.setCurrentIndex(1))
        self.bt_back_main.clicked.connect(lambda:SEMEA.setCurrentIndex(0))
        self.bt_to_aux.clicked.connect(lambda:SEMEA.setCurrentIndex(2))
        self.bt_back_conf.clicked.connect(lambda:SEMEA.setCurrentIndex(1))
        
        QtCore.QMetaObject.connectSlotsByName(SEMEA)

    def retranslateUi(self, SEMEA):
        _translate = QtCore.QCoreApplication.translate
        SEMEA.setWindowTitle(_translate("SEMEA", "SEMEAPY"))
        self.vel_3.setItemText(0, _translate("SEMEA", "0,75"))
        self.vel_3.setItemText(1, _translate("SEMEA", "1,0"))
        self.vel_3.setItemText(2, _translate("SEMEA", "1,25"))
        self.vel_3.setItemText(3, _translate("SEMEA", "1,5"))
        self.label_14.setText(_translate("SEMEA", "Speed(m/s):"))
        self.ql_speed.setPlainText(_translate("SEMEA", "0.0"))
        self.label_11.setText(_translate("SEMEA", " PDOP:"))
        self.ql_pdop.setPlainText(_translate("SEMEA", "0.0"))
        self.label_28.setText(_translate("SEMEA", "Pop.(plants/ha):"))
        self.ql_seed.setPlainText(_translate("SEMEA", "0.0"))
        self.label_29.setText(_translate("SEMEA", "Fertilizer Rt (kg/ha):"))
        self.ql_fert_rt.setPlainText(_translate("SEMEA", "0.0"))
        self.label_31.setText(_translate("SEMEA", "Fertilizer Wgt  (kg):"))
        self.ql_fert_wgt.setPlainText(_translate("SEMEA", "0.0"))
        self.label_32.setText(_translate("SEMEA", "Area(ha):"))
        self.ql_area.setPlainText(_translate("SEMEA", "0.0"))
        self.label_34.setText(_translate("SEMEA", "Op.Cap. (ha/h):"))
        self.ql_opcap.setPlainText(_translate("SEMEA", "0.0"))
        self.exit.setText(_translate("SEMEA", "EXIT"))
        self.lb_status.setText(_translate("SEMEA", "----"))
        SEMEA.setTabText(SEMEA.indexOf(self.main), _translate("SEMEA", "    MAIN    "))
        self.label_23.setText(_translate("SEMEA", "Row spacing (m)"))
        self.m_pop_7.setText(_translate("SEMEA", "-"))
        self.ql_row_spacing.setPlainText(_translate("SEMEA", "0.7"))
        self.m_pop_8.setText(_translate("SEMEA", "+"))
        self.label_20.setText(_translate("SEMEA", "SeedGerm(%):"))
        self.m_pop_5.setText(_translate("SEMEA", "-"))
        self.ql_germ.setPlainText(_translate("SEMEA", "95"))
        self.m_pop_6.setText(_translate("SEMEA", "+"))
        self.label_15.setText(_translate("SEMEA", "# of Disk Holes:"))
        self.list_holes.setItemText(0, _translate("SEMEA", "28"))
        self.list_holes.setItemText(1, _translate("SEMEA", "45"))
        self.list_holes.setItemText(2, _translate("SEMEA", "64"))
        self.list_holes.setItemText(3, _translate("SEMEA", "84"))
        self.label_38.setText(_translate("SEMEA", "Fertilizer (kg/ha):"))
        self.list_fert.setItemText(0, _translate("SEMEA", "OFF"))
        self.list_fert.setItemText(1, _translate("SEMEA", "MAP"))
        self.list_fert.setItemText(2, _translate("SEMEA", "FIX"))
        self.bt_load_fert.setText(_translate("SEMEA", "LOAD MAP"))
        self.m_pop_3.setText(_translate("SEMEA", "-"))
        self.label_25.setText(_translate("SEMEA", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.ql_set_fert.setPlainText(_translate("SEMEA", "300.0"))
        self.m_pop_4.setText(_translate("SEMEA", "+"))
        self.label_36.setText(_translate("SEMEA", "Pop.(plants/ha):"))
        self.list_seed.setItemText(0, _translate("SEMEA", "OFF"))
        self.list_seed.setItemText(1, _translate("SEMEA", "MAP"))
        self.list_seed.setItemText(2, _translate("SEMEA", "FIX"))
        self.bt_load_seed.setText(_translate("SEMEA", "LOAD MAP"))
        self.m_pop.setText(_translate("SEMEA", "-"))
        self.ql_set_pop.setPlainText(_translate("SEMEA", "50000"))
        self.p_pop.setText(_translate("SEMEA", "+"))
        self.label_21.setText(_translate("SEMEA", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        SEMEA.setTabText(SEMEA.indexOf(self.config), _translate("SEMEA", "   CONFIG    "))
        self.cb_motion_simulate.setText(_translate("SEMEA", "Motion Simulation (for test only)"))
        self.label_39.setText(_translate("SEMEA", "Communication Port:"))
        self.list_com_port.setItemText(0, _translate("SEMEA", "/dev/ttyUSB0"))
        self.list_com_port.setItemText(1, _translate("SEMEA", "/dev/ttyUSB1"))
        self.list_com_port.setItemText(2, _translate("SEMEA", "/dev/ttyUSB2"))
        self.label_40.setText(_translate("SEMEA", "Log file :"))
        self.ql_logfile.setPlainText(_translate("SEMEA", "No file defined"))
        self.cb_remote.setText(_translate("SEMEA", "Remote Monitoring           Status:"))
        self.ql_remote_status.setPlainText(_translate("SEMEA", "Not running"))
        self.bt_define_logfile.setText(_translate("SEMEA", "Define log file"))
        self.bt_reload_logfile.setText(_translate("SEMEA", "Reload  log file"))
        self.label_22.setText(_translate("SEMEA", "Simulated Speed (m/s):"))
        self.m_pop_9.setText(_translate("SEMEA", "-"))
        self.ql_sim_speed.setPlainText(_translate("SEMEA", "1.0"))
        self.m_pop_10.setText(_translate("SEMEA", "+"))
        self.bt_tare.setText(_translate("SEMEA", "TARE"))
        self.lb_cal.setText(_translate("SEMEA", "Empty Tank:"))
        self.bt_ok_cal.setText(_translate("SEMEA", "OK"))
        self.bt_calibrate.setText(_translate("SEMEA", "CALIBRATE"))
        SEMEA.setTabText(SEMEA.indexOf(self.aux), _translate("SEMEA", "    AUX        "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SEMEA = QtWidgets.QTabWidget()
    ui = Ui_SEMEA()
    ui.setupUi(SEMEA)
    SEMEA.show()
    sys.exit(app.exec_())

