# -*- coding: utf-8 -*-

# Build the Virtual Numeric KeyBoard, 
# containing 0 to 9 numeric button
# dot (.) button
# clear button
# Enter (OK) button
# Display Number
# The Keyboard GUI it was designed using Qt Designer
# And converted for Python File using pyuic5 command of PyQt5 Tools
#
from PyQt5 import QtCore, QtGui, QtWidgets
#
class Ui_KeyBoard(object):
    def setupUi(self, KeyBoard):
        KeyBoard.setObjectName("KeyBoard")
        KeyBoard.resize(350, 300)
        self.centralWidget = QtWidgets.QWidget(KeyBoard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralWidget.sizePolicy().hasHeightForWidth())
        self.centralWidget.setSizePolicy(sizePolicy)
        self.centralWidget.setObjectName("centralWidget")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralWidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(23, 10, 291, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.layoutWidget = QtWidgets.QWidget(self.centralWidget)
        self.layoutWidget.setGeometry(QtCore.QRect(250, 60, 102, 221))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_cls = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_cls.setMinimumSize(QtCore.QSize(90, 100))
        self.btn_cls.setMaximumSize(QtCore.QSize(90, 16777215))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.btn_cls.setFont(font)
        self.btn_cls.setStyleSheet("QPushButton {\n"
"   color: #FFC107;\n"
"}")
        self.btn_cls.setObjectName("btn_cls")
        self.verticalLayout.addWidget(self.btn_cls)
        self.btn_ok = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_ok.setMinimumSize(QtCore.QSize(90, 100))
        self.btn_ok.setMaximumSize(QtCore.QSize(90, 16777215))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.btn_ok.setFont(font)
        self.btn_ok.setStyleSheet("QPushButton {\n"
"color: #4CAF50;\n"
"}")
        self.btn_ok.setObjectName("btn_ok")
        self.verticalLayout.addWidget(self.btn_ok)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralWidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 60, 239, 221))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.btn_7 = QtWidgets.QPushButton(self.layoutWidget1)
        self.btn_7.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(27)
        font.setBold(True)
        font.setWeight(75)
        self.btn_7.setFont(font)
        self.btn_7.setStyleSheet("QPushButton {\n"
"color: #1976D2;\n"
"}")
        self.btn_7.setObjectName("btn_7")
        self.gridLayout.addWidget(self.btn_7, 0, 0, 1, 1)
        self.btn_8 = QtWidgets.QPushButton(self.layoutWidget1)
        self.btn_8.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(27)
        font.setBold(True)
        font.setWeight(75)
        self.btn_8.setFont(font)
        self.btn_8.setStyleSheet("QPushButton {\n"
"color: #1976D2;\n"
"}")
        self.btn_8.setObjectName("btn_8")
        self.gridLayout.addWidget(self.btn_8, 0, 1, 1, 1)
        self.btn_9 = QtWidgets.QPushButton(self.layoutWidget1)
        self.btn_9.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(27)
        font.setBold(True)
        font.setWeight(75)
        self.btn_9.setFont(font)
        self.btn_9.setStyleSheet("QPushButton {\n"
"color: #1976D2;\n"
"}")
        self.btn_9.setObjectName("btn_9")
        self.gridLayout.addWidget(self.btn_9, 0, 2, 1, 1)
        self.btn_4 = QtWidgets.QPushButton(self.layoutWidget1)
        self.btn_4.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(27)
        font.setBold(True)
        font.setWeight(75)
        self.btn_4.setFont(font)
        self.btn_4.setStyleSheet("QPushButton {\n"
"color: #1976D2;\n"
"}")
        self.btn_4.setObjectName("btn_4")
        self.gridLayout.addWidget(self.btn_4, 1, 0, 1, 1)
        self.btn_5 = QtWidgets.QPushButton(self.layoutWidget1)
        self.btn_5.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(27)
        font.setBold(True)
        font.setWeight(75)
        self.btn_5.setFont(font)
        self.btn_5.setStyleSheet("QPushButton {\n"
"color: #1976D2;\n"
"}")
        self.btn_5.setObjectName("btn_5")
        self.gridLayout.addWidget(self.btn_5, 1, 1, 1, 1)
        self.btn_6 = QtWidgets.QPushButton(self.layoutWidget1)
        self.btn_6.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(27)
        font.setBold(True)
        font.setWeight(75)
        self.btn_6.setFont(font)
        self.btn_6.setStyleSheet("QPushButton {\n"
"color: #1976D2;\n"
"}")
        self.btn_6.setObjectName("btn_6")
        self.gridLayout.addWidget(self.btn_6, 1, 2, 1, 1)
        self.btn_1 = QtWidgets.QPushButton(self.layoutWidget1)
        self.btn_1.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(27)
        font.setBold(True)
        font.setWeight(75)
        self.btn_1.setFont(font)
        self.btn_1.setStyleSheet("QPushButton {\n"
"color: #1976D2;\n"
"}")
        self.btn_1.setObjectName("btn_1")
        self.gridLayout.addWidget(self.btn_1, 2, 0, 1, 1)
        self.btn_2 = QtWidgets.QPushButton(self.layoutWidget1)
        self.btn_2.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(27)
        font.setBold(True)
        font.setWeight(75)
        self.btn_2.setFont(font)
        self.btn_2.setStyleSheet("QPushButton {\n"
"color: #1976D2;\n"
"}")
        self.btn_2.setObjectName("btn_2")
        self.gridLayout.addWidget(self.btn_2, 2, 1, 1, 1)
        self.btn_3 = QtWidgets.QPushButton(self.layoutWidget1)
        self.btn_3.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(27)
        font.setBold(True)
        font.setWeight(75)
        self.btn_3.setFont(font)
        self.btn_3.setStyleSheet("QPushButton {\n"
"color: #1976D2;\n"
"}")
        self.btn_3.setObjectName("btn_3")
        self.gridLayout.addWidget(self.btn_3, 2, 2, 1, 1)
        self.btn_dot = QtWidgets.QPushButton(self.layoutWidget1)
        self.btn_dot.setMinimumSize(QtCore.QSize(0, 50))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 104, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 104, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 104, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.btn_dot.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(27)
        font.setBold(False)
        font.setWeight(50)
        self.btn_dot.setFont(font)
        self.btn_dot.setObjectName("btn_dot")
        self.gridLayout.addWidget(self.btn_dot, 3, 0, 1, 1)
        self.btn_0 = QtWidgets.QPushButton(self.layoutWidget1)
        self.btn_0.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(27)
        font.setBold(True)
        font.setWeight(75)
        self.btn_0.setFont(font)
        self.btn_0.setStyleSheet("QPushButton {\n"
"color: #1976D2;\n"
"}")
        self.btn_0.setObjectName("btn_0")
        self.gridLayout.addWidget(self.btn_0, 3, 1, 1, 1)
        KeyBoard.setCentralWidget(self.centralWidget)
        self.actionExit = QtWidgets.QAction(KeyBoard)
        self.actionExit.setObjectName("actionExit")
        self.actionReset = QtWidgets.QAction(KeyBoard)
        self.actionReset.setObjectName("actionReset")

        self.retranslateUi(KeyBoard)
        QtCore.QMetaObject.connectSlotsByName(KeyBoard)

    def retranslateUi(self, KeyBoard):
        _translate = QtCore.QCoreApplication.translate
        KeyBoard.setWindowTitle(_translate("KeyBoard", "Keyboard"))
        self.plainTextEdit.setPlainText(_translate("KeyBoard", "123456.8"))
        self.btn_cls.setText(_translate("KeyBoard", "CLEAR"))
        self.btn_cls.setShortcut(_translate("KeyBoard", "R"))
        self.btn_ok.setText(_translate("KeyBoard", "OK"))
        self.btn_ok.setShortcut(_translate("KeyBoard", "Return"))
        self.btn_7.setText(_translate("KeyBoard", "7"))
        self.btn_7.setShortcut(_translate("KeyBoard", "7"))
        self.btn_8.setText(_translate("KeyBoard", "8"))
        self.btn_8.setShortcut(_translate("KeyBoard", "8"))
        self.btn_9.setText(_translate("KeyBoard", "9"))
        self.btn_9.setShortcut(_translate("KeyBoard", "9"))
        self.btn_4.setText(_translate("KeyBoard", "4"))
        self.btn_4.setShortcut(_translate("KeyBoard", "4"))
        self.btn_5.setText(_translate("KeyBoard", "5"))
        self.btn_5.setShortcut(_translate("KeyBoard", "5"))
        self.btn_6.setText(_translate("KeyBoard", "6"))
        self.btn_6.setShortcut(_translate("KeyBoard", "6"))
        self.btn_1.setText(_translate("KeyBoard", "1"))
        self.btn_1.setShortcut(_translate("KeyBoard", "1"))
        self.btn_2.setText(_translate("KeyBoard", "2"))
        self.btn_2.setShortcut(_translate("KeyBoard", "2"))
        self.btn_3.setText(_translate("KeyBoard", "3"))
        self.btn_3.setShortcut(_translate("KeyBoard", "3"))
        self.btn_dot.setText(_translate("KeyBoard", "."))
        self.btn_dot.setShortcut(_translate("KeyBoard", "-"))
        self.btn_0.setText(_translate("KeyBoard", "0"))
        self.btn_0.setShortcut(_translate("KeyBoard", "0"))
        self.actionExit.setText(_translate("KeyBoard", "Exit"))
        self.actionExit.setShortcut(_translate("KeyBoard", "Ctrl+Q"))
        self.actionReset.setText(_translate("KeyBoard", "Reset"))
        self.actionReset.setShortcut(_translate("KeyBoard", "Ctrl+R"))
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    KeyBoard = QtWidgets.QMainWindow()
    ui = Ui_KeyBoard()
    ui.setupUi(KeyBoard)
    KeyBoard.show()
    sys.exit(app.exec_())

