# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'seeder_ui.ui'
#
# Created: Tue Apr 23 00:04:25 2019
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import os

class Ui_SEMEA(object):
    def setupUi(self, SEMEA):
        SEMEA.setObjectName("SEMEA")
        SEMEA.resize(800, 430)
        font = QtGui.QFont()
        font.setPointSize(12)
        SEMEA.setFont(font)
        icon = QtGui.QIcon()
        self.dir=os.path.dirname(os.path.abspath(__file__))
        icon.addPixmap(QtGui.QPixmap(os.path.join(self.dir,"icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SEMEA.setWindowIcon(icon)
        SEMEA.setTabPosition(QtWidgets.QTabWidget.North)
        self.main = QtWidgets.QWidget()
        self.main.setObjectName("main")
        self.vel_3 = QtWidgets.QComboBox(self.main)
        self.vel_3.setGeometry(QtCore.QRect(910, 120, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.vel_3.setFont(font)
        self.vel_3.setObjectName("vel_3")
        self.vel_3.addItem("")
        self.vel_3.addItem("")
        self.vel_3.addItem("")
        self.vel_3.addItem("")
        self.gv = QtWidgets.QGraphicsView(self.main)
        self.gv.setGeometry(QtCore.QRect(20, 10, 481, 291))
        self.gv.setObjectName("gv")
        self.layoutWidget_2 = QtWidgets.QWidget(self.main)
        self.layoutWidget_2.setGeometry(QtCore.QRect(518, 10, 261, 336))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_14 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_2.addWidget(self.label_14)
        self.ql_speed = QtWidgets.QPlainTextEdit(self.layoutWidget_2)
        self.ql_speed.setMaximumSize(QtCore.QSize(80, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ql_speed.setFont(font)
        self.ql_speed.setPlainText("")
        self.ql_speed.setObjectName("ql_speed")
        self.horizontalLayout_2.addWidget(self.ql_speed)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_11 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_3.addWidget(self.label_11)
        self.ql_pdop = QtWidgets.QPlainTextEdit(self.layoutWidget_2)
        self.ql_pdop.setMaximumSize(QtCore.QSize(80, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ql_pdop.setFont(font)
        self.ql_pdop.setPlainText("")
        self.ql_pdop.setObjectName("ql_pdop")
        self.horizontalLayout_3.addWidget(self.ql_pdop)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_28 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_4.addWidget(self.label_28)
        self.ql_seed = QtWidgets.QPlainTextEdit(self.layoutWidget_2)
        self.ql_seed.setMaximumSize(QtCore.QSize(80, 30))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 104, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.ql_seed.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ql_seed.setFont(font)
        self.ql_seed.setPlainText("")
        self.ql_seed.setObjectName("ql_seed")
        self.horizontalLayout_4.addWidget(self.ql_seed)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_29 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_5.addWidget(self.label_29)
        self.ql_fert_rt = QtWidgets.QPlainTextEdit(self.layoutWidget_2)
        self.ql_fert_rt.setMaximumSize(QtCore.QSize(80, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ql_fert_rt.setFont(font)
        self.ql_fert_rt.setPlainText("")
        self.ql_fert_rt.setObjectName("ql_fert_rt")
        self.horizontalLayout_5.addWidget(self.ql_fert_rt)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_31 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_7.addWidget(self.label_31)
        self.ql_fert_wgt = QtWidgets.QPlainTextEdit(self.layoutWidget_2)
        self.ql_fert_wgt.setMaximumSize(QtCore.QSize(80, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ql_fert_wgt.setFont(font)
        self.ql_fert_wgt.setPlainText("")
        self.ql_fert_wgt.setObjectName("ql_fert_wgt")
        self.horizontalLayout_7.addWidget(self.ql_fert_wgt)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_32 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_8.addWidget(self.label_32)
        self.ql_area = QtWidgets.QPlainTextEdit(self.layoutWidget_2)
        self.ql_area.setMaximumSize(QtCore.QSize(80, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ql_area.setFont(font)
        self.ql_area.setPlainText("")
        self.ql_area.setObjectName("ql_area")
        self.horizontalLayout_8.addWidget(self.ql_area)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_34 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.horizontalLayout_9.addWidget(self.label_34)
        self.ql_opcap = QtWidgets.QPlainTextEdit(self.layoutWidget_2)
        self.ql_opcap.setMaximumSize(QtCore.QSize(80, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ql_opcap.setFont(font)
        self.ql_opcap.setPlainText("")
        self.ql_opcap.setObjectName("ql_opcap")
        self.horizontalLayout_9.addWidget(self.ql_opcap)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.exit = QtWidgets.QPushButton(self.main)
        self.exit.setGeometry(QtCore.QRect(20, 310, 120, 81))
        self.exit.setMinimumSize(QtCore.QSize(0, 75))
        self.exit.setMaximumSize(QtCore.QSize(120, 90))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.exit.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(os.path.join(self.dir,"exit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exit.setIcon(icon1)
        self.exit.setIconSize(QtCore.QSize(64, 54))
        self.exit.setObjectName("exit")
        self.bt_to_conf = QtWidgets.QPushButton(self.main)
        self.bt_to_conf.setGeometry(QtCore.QRect(150, 310, 120, 80))
        self.bt_to_conf.setMinimumSize(QtCore.QSize(120, 80))
        self.bt_to_conf.setMaximumSize(QtCore.QSize(120, 80))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.bt_to_conf.setFont(font)
        self.bt_to_conf.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(os.path.join(self.dir,"go.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_to_conf.setIcon(icon2)
        self.bt_to_conf.setIconSize(QtCore.QSize(64, 64))
        self.bt_to_conf.setObjectName("bt_to_conf")
        self.lb_status = QtWidgets.QLabel(self.main)
        self.lb_status.setGeometry(QtCore.QRect(290, 360, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lb_status.setFont(font)
        self.lb_status.setObjectName("lb_status")
        self.lb_datetime = QtWidgets.QLabel(self.main)
        self.lb_datetime.setGeometry(QtCore.QRect(520, 360, 256, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lb_datetime.setFont(font)
        self.lb_datetime.setObjectName("lb_datetime")
        self.frame_9 = QtWidgets.QFrame(self.main)
        self.frame_9.setGeometry(QtCore.QRect(510, 5, 281, 346))
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.frame_10 = QtWidgets.QFrame(self.main)
        self.frame_10.setGeometry(QtCore.QRect(284, 354, 506, 36))
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.lb_tb = QtWidgets.QLabel(self.main)
        self.lb_tb.setGeometry(QtCore.QRect(290, 310, 201, 36))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 104, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 104, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.lb_tb.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lb_tb.setFont(font)
        self.lb_tb.setObjectName("lb_tb")
        SEMEA.addTab(self.main, "")
        self.config = QtWidgets.QWidget()
        self.config.setObjectName("config")
        self.bt_back_main = QtWidgets.QPushButton(self.config)
        self.bt_back_main.setGeometry(QtCore.QRect(635, 175, 150, 80))
        self.bt_back_main.setMinimumSize(QtCore.QSize(150, 80))
        self.bt_back_main.setMaximumSize(QtCore.QSize(150, 80))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.bt_back_main.setFont(font)
        self.bt_back_main.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(os.path.join(self.dir,"back.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_back_main.setIcon(icon3)
        self.bt_back_main.setIconSize(QtCore.QSize(64, 64))
        self.bt_back_main.setObjectName("bt_back_main")
        self.bt_to_conf_2 = QtWidgets.QPushButton(self.config)
        self.bt_to_conf_2.setGeometry(QtCore.QRect(635, 290, 150, 80))
        self.bt_to_conf_2.setMinimumSize(QtCore.QSize(150, 80))
        self.bt_to_conf_2.setMaximumSize(QtCore.QSize(150, 80))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.bt_to_conf_2.setFont(font)
        self.bt_to_conf_2.setText("")
        self.bt_to_conf_2.setIcon(icon2)
        self.bt_to_conf_2.setIconSize(QtCore.QSize(64, 64))
        self.bt_to_conf_2.setObjectName("bt_to_conf_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.config)
        self.groupBox_3.setGeometry(QtCore.QRect(5, 230, 611, 166))
        self.groupBox_3.setObjectName("groupBox_3")
        self.layoutWidget_4 = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget_4.setGeometry(QtCore.QRect(10, 20, 593, 141))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.layoutWidget_4)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_38 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_38.setObjectName("horizontalLayout_38")
        self.horizontalLayout_39 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_39.setObjectName("horizontalLayout_39")
        self.label_43 = QtWidgets.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_43.setFont(font)
        self.label_43.setObjectName("label_43")
        self.horizontalLayout_39.addWidget(self.label_43)
        self.le_set_mach_id = ClickableLineEdit(self.layoutWidget_4)
        self.le_set_mach_id.setMinimumSize(QtCore.QSize(150, 40))
        self.le_set_mach_id.setMaximumSize(QtCore.QSize(150, 40))
        self.le_set_mach_id.setObjectName("le_set_mach_id")
        self.horizontalLayout_39.addWidget(self.le_set_mach_id)
        self.horizontalLayout_38.addLayout(self.horizontalLayout_39)
        self.horizontalLayout_40 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_40.setObjectName("horizontalLayout_40")
        self.label_58 = QtWidgets.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_58.setFont(font)
        self.label_58.setObjectName("label_58")
        self.horizontalLayout_40.addWidget(self.label_58)
        self.le_set_fil_id = ClickableLineEdit(self.layoutWidget_4)
        self.le_set_fil_id.setMinimumSize(QtCore.QSize(150, 40))
        self.le_set_fil_id.setMaximumSize(QtCore.QSize(150, 40))
        self.le_set_fil_id.setObjectName("le_set_fil_id")
        self.horizontalLayout_40.addWidget(self.le_set_fil_id)
        self.horizontalLayout_38.addLayout(self.horizontalLayout_40)
        self.bt_st_id = QtWidgets.QPushButton(self.layoutWidget_4)
        self.bt_st_id.setMinimumSize(QtCore.QSize(0, 40))
        self.bt_st_id.setMaximumSize(QtCore.QSize(16777215, 40))
        self.bt_st_id.setObjectName("bt_st_id")
        self.horizontalLayout_38.addWidget(self.bt_st_id)
        self.verticalLayout_8.addLayout(self.horizontalLayout_38)
        self.line_14 = QtWidgets.QFrame(self.layoutWidget_4)
        self.line_14.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.verticalLayout_8.addWidget(self.line_14)
        self.horizontalLayout_41 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_41.setObjectName("horizontalLayout_41")
        self.label_59 = QtWidgets.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_59.setFont(font)
        self.label_59.setObjectName("label_59")
        self.horizontalLayout_41.addWidget(self.label_59)
        self.ql_logfile = QtWidgets.QPlainTextEdit(self.layoutWidget_4)
        self.ql_logfile.setMinimumSize(QtCore.QSize(440, 0))
        self.ql_logfile.setMaximumSize(QtCore.QSize(4490, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ql_logfile.setFont(font)
        self.ql_logfile.setPlainText("")
        self.ql_logfile.setObjectName("ql_logfile")
        self.horizontalLayout_41.addWidget(self.ql_logfile)
        self.verticalLayout_8.addLayout(self.horizontalLayout_41)
        self.line_15 = QtWidgets.QFrame(self.layoutWidget_4)
        self.line_15.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.verticalLayout_8.addWidget(self.line_15)
        self.horizontalLayout_42 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_42.setObjectName("horizontalLayout_42")
        self.label_60 = QtWidgets.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_60.setFont(font)
        self.label_60.setObjectName("label_60")
        self.horizontalLayout_42.addWidget(self.label_60)
        self.bt_remote = QtWidgets.QPushButton(self.layoutWidget_4)
        self.bt_remote.setMinimumSize(QtCore.QSize(0, 30))
        self.bt_remote.setMaximumSize(QtCore.QSize(16777215, 30))
        self.bt_remote.setObjectName("bt_remote")
        self.horizontalLayout_42.addWidget(self.bt_remote)
        self.ql_remote_status = QtWidgets.QPlainTextEdit(self.layoutWidget_4)
        self.ql_remote_status.setMinimumSize(QtCore.QSize(200, 0))
        self.ql_remote_status.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ql_remote_status.setFont(font)
        self.ql_remote_status.setPlainText("")
        self.ql_remote_status.setObjectName("ql_remote_status")
        self.horizontalLayout_42.addWidget(self.ql_remote_status)
        self.verticalLayout_8.addLayout(self.horizontalLayout_42)
        self.groupBox_2 = QtWidgets.QGroupBox(self.config)
        self.groupBox_2.setGeometry(QtCore.QRect(5, 145, 611, 80))
        self.groupBox_2.setObjectName("groupBox_2")
        self.layoutWidget_9 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget_9.setGeometry(QtCore.QRect(10, 20, 583, 51))
        self.layoutWidget_9.setObjectName("layoutWidget_9")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.layoutWidget_9)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_38 = QtWidgets.QLabel(self.layoutWidget_9)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_38.setFont(font)
        self.label_38.setObjectName("label_38")
        self.horizontalLayout_14.addWidget(self.label_38)
        self.bt_load_fert = QtWidgets.QPushButton(self.layoutWidget_9)
        self.bt_load_fert.setMinimumSize(QtCore.QSize(150, 40))
        self.bt_load_fert.setMaximumSize(QtCore.QSize(150, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.bt_load_fert.setFont(font)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(os.path.join(self.dir,"file.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_load_fert.setIcon(icon4)
        self.bt_load_fert.setIconSize(QtCore.QSize(32, 32))
        self.bt_load_fert.setObjectName("bt_load_fert")
        self.horizontalLayout_14.addWidget(self.bt_load_fert)
        self.le_set_fertrt = ClickableLineEdit(self.layoutWidget_9)
        self.le_set_fertrt.setMinimumSize(QtCore.QSize(120, 40))
        self.le_set_fertrt.setMaximumSize(QtCore.QSize(120, 40))
        self.le_set_fertrt.setObjectName("le_set_fertrt")
        self.horizontalLayout_14.addWidget(self.le_set_fertrt)
        self.fert_off = QtWidgets.QPushButton(self.layoutWidget_9)
        self.fert_off.setMinimumSize(QtCore.QSize(150, 40))
        self.fert_off.setMaximumSize(QtCore.QSize(150, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.fert_off.setFont(font)
        self.fert_off.setObjectName("fert_off")
        self.horizontalLayout_14.addWidget(self.fert_off)
        self.groupBox = QtWidgets.QGroupBox(self.config)
        self.groupBox.setGeometry(QtCore.QRect(5, 0, 786, 141))
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(12, 22, 761, 111))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_36 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_36.setFont(font)
        self.label_36.setObjectName("label_36")
        self.horizontalLayout_11.addWidget(self.label_36)
        self.bt_load_seed = QtWidgets.QPushButton(self.layoutWidget)
        self.bt_load_seed.setMinimumSize(QtCore.QSize(200, 40))
        self.bt_load_seed.setMaximumSize(QtCore.QSize(200, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.bt_load_seed.setFont(font)
        self.bt_load_seed.setIcon(icon4)
        self.bt_load_seed.setIconSize(QtCore.QSize(32, 32))
        self.bt_load_seed.setObjectName("bt_load_seed")
        self.horizontalLayout_11.addWidget(self.bt_load_seed)
        self.le_set_pop = ClickableLineEdit(self.layoutWidget)
        self.le_set_pop.setMinimumSize(QtCore.QSize(120, 40))
        self.le_set_pop.setMaximumSize(QtCore.QSize(120, 40))
        self.le_set_pop.setObjectName("le_set_pop")
        self.horizontalLayout_11.addWidget(self.le_set_pop)
        self.pop_off = QtWidgets.QPushButton(self.layoutWidget)
        self.pop_off.setMinimumSize(QtCore.QSize(200, 40))
        self.pop_off.setMaximumSize(QtCore.QSize(200, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pop_off.setFont(font)
        self.pop_off.setObjectName("pop_off")
        self.horizontalLayout_11.addWidget(self.pop_off)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.label_20 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_27.addWidget(self.label_20)
        self.le_set_germ = ClickableLineEdit(self.layoutWidget)
        self.le_set_germ.setMinimumSize(QtCore.QSize(150, 40))
        self.le_set_germ.setMaximumSize(QtCore.QSize(150, 40))
        self.le_set_germ.setObjectName("le_set_germ")
        self.horizontalLayout_27.addWidget(self.le_set_germ)
        self.horizontalLayout_28.addLayout(self.horizontalLayout_27)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_23 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_13.addWidget(self.label_23)
        self.le_row_spacing = ClickableLineEdit(self.layoutWidget)
        self.le_row_spacing.setMinimumSize(QtCore.QSize(150, 40))
        self.le_row_spacing.setMaximumSize(QtCore.QSize(120, 40))
        self.le_row_spacing.setObjectName("le_row_spacing")
        self.horizontalLayout_13.addWidget(self.le_row_spacing)
        self.label_15 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_13.addWidget(self.label_15)
        self.list_holes = QtWidgets.QComboBox(self.layoutWidget)
        self.list_holes.setMinimumSize(QtCore.QSize(100, 30))
        self.list_holes.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.list_holes.setFont(font)
        self.list_holes.setObjectName("list_holes")
        self.list_holes.addItem("")
        self.list_holes.addItem("")
        self.list_holes.addItem("")
        self.list_holes.addItem("")
        self.horizontalLayout_13.addWidget(self.list_holes)
        self.horizontalLayout_28.addLayout(self.horizontalLayout_13)
        self.verticalLayout_3.addLayout(self.horizontalLayout_28)
        SEMEA.addTab(self.config, "")
        self.aux = QtWidgets.QWidget()
        self.aux.setObjectName("aux")
        self.bt_back_conf = QtWidgets.QPushButton(self.aux)
        self.bt_back_conf.setGeometry(QtCore.QRect(585, 285, 150, 80))
        self.bt_back_conf.setMinimumSize(QtCore.QSize(150, 80))
        self.bt_back_conf.setMaximumSize(QtCore.QSize(150, 80))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.bt_back_conf.setFont(font)
        self.bt_back_conf.setText("")
        self.bt_back_conf.setIcon(icon3)
        self.bt_back_conf.setIconSize(QtCore.QSize(64, 64))
        self.bt_back_conf.setObjectName("bt_back_conf")
        self.groupBox_5 = QtWidgets.QGroupBox(self.aux)
        self.groupBox_5.setGeometry(QtCore.QRect(525, 5, 261, 266))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName("groupBox_5")
        self.layoutWidget_8 = QtWidgets.QWidget(self.groupBox_5)
        self.layoutWidget_8.setGeometry(QtCore.QRect(10, 25, 236, 226))
        self.layoutWidget_8.setObjectName("layoutWidget_8")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget_8)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.lb_cal = QtWidgets.QLabel(self.layoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lb_cal.setFont(font)
        self.lb_cal.setObjectName("lb_cal")
        self.horizontalLayout_17.addWidget(self.lb_cal)
        self.list_cal_wgt = QtWidgets.QComboBox(self.layoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.list_cal_wgt.setFont(font)
        self.list_cal_wgt.setObjectName("list_cal_wgt")
        self.list_cal_wgt.addItem("")
        self.list_cal_wgt.addItem("")
        self.list_cal_wgt.addItem("")
        self.list_cal_wgt.addItem("")
        self.horizontalLayout_17.addWidget(self.list_cal_wgt)
        self.verticalLayout_2.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_44 = QtWidgets.QLabel(self.layoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_44.setFont(font)
        self.label_44.setObjectName("label_44")
        self.horizontalLayout_19.addWidget(self.label_44)
        self.qd_voltage_cal = QtWidgets.QPlainTextEdit(self.layoutWidget_8)
        self.qd_voltage_cal.setMinimumSize(QtCore.QSize(30, 0))
        self.qd_voltage_cal.setMaximumSize(QtCore.QSize(80, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.qd_voltage_cal.setFont(font)
        self.qd_voltage_cal.setPlainText("")
        self.qd_voltage_cal.setObjectName("qd_voltage_cal")
        self.horizontalLayout_19.addWidget(self.qd_voltage_cal)
        self.verticalLayout_2.addLayout(self.horizontalLayout_19)
        self.bt_save_cal = QtWidgets.QPushButton(self.layoutWidget_8)
        self.bt_save_cal.setMinimumSize(QtCore.QSize(0, 50))
        self.bt_save_cal.setObjectName("bt_save_cal")
        self.verticalLayout_2.addWidget(self.bt_save_cal)
        self.bt_calibrate = QtWidgets.QPushButton(self.layoutWidget_8)
        self.bt_calibrate.setMinimumSize(QtCore.QSize(0, 50))
        self.bt_calibrate.setObjectName("bt_calibrate")
        self.verticalLayout_2.addWidget(self.bt_calibrate)
        self.groupBox_8 = QtWidgets.QGroupBox(self.aux)
        self.groupBox_8.setGeometry(QtCore.QRect(10, 270, 496, 126))
        self.groupBox_8.setObjectName("groupBox_8")
        self.layoutWidget_3 = QtWidgets.QWidget(self.groupBox_8)
        self.layoutWidget_3.setGeometry(QtCore.QRect(5, 20, 481, 96))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.label_54 = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_54.setFont(font)
        self.label_54.setObjectName("label_54")
        self.horizontalLayout_33.addWidget(self.label_54)
        self.le_set_t_ctrl = ClickableLineEdit(self.layoutWidget_3)
        self.le_set_t_ctrl.setMinimumSize(QtCore.QSize(120, 40))
        self.le_set_t_ctrl.setMaximumSize(QtCore.QSize(120, 40))
        self.le_set_t_ctrl.setObjectName("le_set_t_ctrl")
        self.horizontalLayout_33.addWidget(self.le_set_t_ctrl)
        self.horizontalLayout_29.addLayout(self.horizontalLayout_33)
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.label_55 = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_55.setFont(font)
        self.label_55.setObjectName("label_55")
        self.horizontalLayout_34.addWidget(self.label_55)
        self.le_set_t_gps = ClickableLineEdit(self.layoutWidget_3)
        self.le_set_t_gps.setMinimumSize(QtCore.QSize(120, 40))
        self.le_set_t_gps.setMaximumSize(QtCore.QSize(120, 40))
        self.le_set_t_gps.setObjectName("le_set_t_gps")
        self.horizontalLayout_34.addWidget(self.le_set_t_gps)
        self.horizontalLayout_29.addLayout(self.horizontalLayout_34)
        self.verticalLayout_4.addLayout(self.horizontalLayout_29)
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        self.label_56 = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_56.setFont(font)
        self.label_56.setObjectName("label_56")
        self.horizontalLayout_36.addWidget(self.label_56)
        self.le_set_latitude = ClickableLineEdit(self.layoutWidget_3)
        self.le_set_latitude.setMinimumSize(QtCore.QSize(120, 40))
        self.le_set_latitude.setMaximumSize(QtCore.QSize(120, 40))
        self.le_set_latitude.setObjectName("le_set_latitude")
        self.horizontalLayout_36.addWidget(self.le_set_latitude)
        self.horizontalLayout_35.addLayout(self.horizontalLayout_36)
        self.horizontalLayout_37 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        self.label_57 = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_57.setFont(font)
        self.label_57.setObjectName("label_57")
        self.horizontalLayout_37.addWidget(self.label_57)
        self.le_set_longitude = ClickableLineEdit(self.layoutWidget_3)
        self.le_set_longitude.setMinimumSize(QtCore.QSize(120, 40))
        self.le_set_longitude.setMaximumSize(QtCore.QSize(120, 40))
        self.le_set_longitude.setObjectName("le_set_longitude")
        self.horizontalLayout_37.addWidget(self.le_set_longitude)
        self.horizontalLayout_35.addLayout(self.horizontalLayout_37)
        self.verticalLayout_4.addLayout(self.horizontalLayout_35)
        self.groupBox_7 = QtWidgets.QGroupBox(self.aux)
        self.groupBox_7.setGeometry(QtCore.QRect(10, 135, 496, 126))
        self.groupBox_7.setObjectName("groupBox_7")
        self.layoutWidget_7 = QtWidgets.QWidget(self.groupBox_7)
        self.layoutWidget_7.setGeometry(QtCore.QRect(10, 20, 476, 94))
        self.layoutWidget_7.setObjectName("layoutWidget_7")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget_7)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_50 = QtWidgets.QLabel(self.layoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_50.setFont(font)
        self.label_50.setObjectName("label_50")
        self.horizontalLayout_21.addWidget(self.label_50)
        self.le_fert_dt = ClickableLineEdit(self.layoutWidget_7)
        self.le_fert_dt.setMinimumSize(QtCore.QSize(150, 40))
        self.le_fert_dt.setMaximumSize(QtCore.QSize(150, 40))
        self.le_fert_dt.setObjectName("le_fert_dt")
        self.horizontalLayout_21.addWidget(self.le_fert_dt)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem)
        self.verticalLayout_5.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_51 = QtWidgets.QLabel(self.layoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_51.setFont(font)
        self.label_51.setObjectName("label_51")
        self.horizontalLayout_22.addWidget(self.label_51)
        self.le_fert_mass = ClickableLineEdit(self.layoutWidget_7)
        self.le_fert_mass.setMinimumSize(QtCore.QSize(80, 40))
        self.le_fert_mass.setMaximumSize(QtCore.QSize(80, 40))
        self.le_fert_mass.setObjectName("le_fert_mass")
        self.horizontalLayout_22.addWidget(self.le_fert_mass)
        self.save_cal_fert = QtWidgets.QPushButton(self.layoutWidget_7)
        self.save_cal_fert.setMinimumSize(QtCore.QSize(120, 0))
        self.save_cal_fert.setMaximumSize(QtCore.QSize(120, 60))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.save_cal_fert.setFont(font)
        self.save_cal_fert.setObjectName("save_cal_fert")
        self.horizontalLayout_22.addWidget(self.save_cal_fert)
        self.verticalLayout_5.addLayout(self.horizontalLayout_22)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.cal_fert = QtWidgets.QPushButton(self.layoutWidget_7)
        self.cal_fert.setMinimumSize(QtCore.QSize(150, 0))
        self.cal_fert.setMaximumSize(QtCore.QSize(150, 80))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cal_fert.setFont(font)
        self.cal_fert.setObjectName("cal_fert")
        self.horizontalLayout.addWidget(self.cal_fert)
        self.groupBox_6 = QtWidgets.QGroupBox(self.aux)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 5, 496, 126))
        self.groupBox_6.setObjectName("groupBox_6")
        self.layoutWidget_6 = QtWidgets.QWidget(self.groupBox_6)
        self.layoutWidget_6.setGeometry(QtCore.QRect(15, 23, 471, 96))
        self.layoutWidget_6.setObjectName("layoutWidget_6")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.layoutWidget_6)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.label_52 = QtWidgets.QLabel(self.layoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_52.setFont(font)
        self.label_52.setObjectName("label_52")
        self.horizontalLayout_30.addWidget(self.label_52)
        self.le_seed_dt = ClickableLineEdit(self.layoutWidget_6)
        self.le_seed_dt.setMinimumSize(QtCore.QSize(150, 40))
        self.le_seed_dt.setMaximumSize(QtCore.QSize(150, 40))
        self.le_seed_dt.setObjectName("le_seed_dt")
        self.horizontalLayout_30.addWidget(self.le_seed_dt)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_30.addItem(spacerItem1)
        self.verticalLayout_6.addLayout(self.horizontalLayout_30)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_53 = QtWidgets.QLabel(self.layoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_53.setFont(font)
        self.label_53.setObjectName("label_53")
        self.horizontalLayout_24.addWidget(self.label_53)
        self.ql_speed_cal = QtWidgets.QPlainTextEdit(self.layoutWidget_6)
        self.ql_speed_cal.setMinimumSize(QtCore.QSize(80, 35))
        self.ql_speed_cal.setMaximumSize(QtCore.QSize(80, 35))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ql_speed_cal.setFont(font)
        self.ql_speed_cal.setPlainText("")
        self.ql_speed_cal.setObjectName("ql_speed_cal")
        self.horizontalLayout_24.addWidget(self.ql_speed_cal)
        self.save_cal_seed = QtWidgets.QPushButton(self.layoutWidget_6)
        self.save_cal_seed.setMinimumSize(QtCore.QSize(120, 0))
        self.save_cal_seed.setMaximumSize(QtCore.QSize(120, 60))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.save_cal_seed.setFont(font)
        self.save_cal_seed.setObjectName("save_cal_seed")
        self.horizontalLayout_24.addWidget(self.save_cal_seed)
        self.verticalLayout_6.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_12.addLayout(self.verticalLayout_6)
        self.cal_seed = QtWidgets.QPushButton(self.layoutWidget_6)
        self.cal_seed.setMinimumSize(QtCore.QSize(150, 0))
        self.cal_seed.setMaximumSize(QtCore.QSize(150, 80))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cal_seed.setFont(font)
        self.cal_seed.setObjectName("cal_seed")
        self.horizontalLayout_12.addWidget(self.cal_seed)
        SEMEA.addTab(self.aux, "")

        self.retranslateUi(SEMEA)
        SEMEA.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(SEMEA)
        self.bt_to_conf.clicked.connect(lambda:SEMEA.setCurrentIndex(1))
        self.bt_back_main.clicked.connect(lambda:SEMEA.setCurrentIndex(0))
        self.bt_to_conf_2.clicked.connect(lambda:SEMEA.setCurrentIndex(2))
        self.bt_back_conf.clicked.connect(lambda:SEMEA.setCurrentIndex(1))

    def retranslateUi(self, SEMEA):
        _translate = QtCore.QCoreApplication.translate
        SEMEA.setWindowTitle(_translate("SEMEA", "SEMEAPY"))
        self.vel_3.setItemText(0, _translate("SEMEA", "0,75"))
        self.vel_3.setItemText(1, _translate("SEMEA", "1,0"))
        self.vel_3.setItemText(2, _translate("SEMEA", "1,25"))
        self.vel_3.setItemText(3, _translate("SEMEA", "1,5"))
        self.label_14.setText(_translate("SEMEA", "Speed(m/s):"))
        self.label_11.setText(_translate("SEMEA", " GPS Status:"))
        self.label_28.setText(_translate("SEMEA", "Pop.(plants/ha):"))
        self.label_29.setText(_translate("SEMEA", "Fertilizer Rt (kg/ha):"))
        self.label_31.setText(_translate("SEMEA", "Fertilizer Wgt  (kg):"))
        self.label_32.setText(_translate("SEMEA", "Area(m²):"))
        self.label_34.setText(_translate("SEMEA", "Time Operation (h):"))
        self.exit.setText(_translate("SEMEA", "EXIT"))
        self.lb_status.setText(_translate("SEMEA", "-------------------------------------------------"))
        self.lb_datetime.setText(_translate("SEMEA", "----------------------------------------------"))
        self.lb_tb.setText(_translate("SEMEA", "000"))
        SEMEA.setTabText(SEMEA.indexOf(self.main), _translate("SEMEA", "    MAIN    "))
        self.groupBox_3.setTitle(_translate("SEMEA", "MONITORING"))
        self.label_43.setText(_translate("SEMEA", "Machine ID :"))
        self.label_58.setText(_translate("SEMEA", "Field ID:"))
        self.bt_st_id.setText(_translate("SEMEA", "SETTING ID\'S"))
        self.label_59.setText(_translate("SEMEA", "Log file :"))
        self.label_60.setText(_translate("SEMEA", "Remote Monitoring:"))
        self.bt_remote.setText(_translate("SEMEA", "START/STOP"))
        self.groupBox_2.setTitle(_translate("SEMEA", "FERTILIZER"))
        self.label_38.setText(_translate("SEMEA", "Fertilizer (kg/ha):    "))
        self.bt_load_fert.setText(_translate("SEMEA", "LOAD MAP"))
        self.fert_off.setText(_translate("SEMEA", "OFF"))
        self.groupBox.setTitle(_translate("SEMEA", "SEEDER"))
        self.label_36.setText(_translate("SEMEA", "Population (plants/ha):"))
        self.bt_load_seed.setText(_translate("SEMEA", "LOAD MAP"))
        self.pop_off.setText(_translate("SEMEA", "OFF"))
        self.label_20.setText(_translate("SEMEA", "SeedGerm(%):"))
        self.label_23.setText(_translate("SEMEA", "Row spacing (m)"))
        self.label_15.setText(_translate("SEMEA", " # of Holes:"))
        self.list_holes.setItemText(0, _translate("SEMEA", "28"))
        self.list_holes.setItemText(1, _translate("SEMEA", "45"))
        self.list_holes.setItemText(2, _translate("SEMEA", "64"))
        self.list_holes.setItemText(3, _translate("SEMEA", "84"))
        SEMEA.setTabText(SEMEA.indexOf(self.config), _translate("SEMEA", "OPERATION"))
        self.groupBox_5.setTitle(_translate("SEMEA", "LOAD CELL"))
        self.lb_cal.setText(_translate("SEMEA", "Weight:"))
        self.list_cal_wgt.setItemText(0, _translate("SEMEA", "Empty Tank"))
        self.list_cal_wgt.setItemText(1, _translate("SEMEA", "Tank + 5kg "))
        self.list_cal_wgt.setItemText(2, _translate("SEMEA", "Tank + 10 kg"))
        self.list_cal_wgt.setItemText(3, _translate("SEMEA", "Tank + 15 kg"))
        self.label_44.setText(_translate("SEMEA", "Voltage Signal (V):"))
        self.bt_save_cal.setText(_translate("SEMEA", "SAVE  POINT"))
        self.bt_calibrate.setText(_translate("SEMEA", "CALIBRATE"))
        self.groupBox_8.setTitle(_translate("SEMEA", "TIMERS AND GPS POSITION TEST"))
        self.label_54.setText(_translate("SEMEA", "Time Control:"))
        self.label_55.setText(_translate("SEMEA", "Time GPS:"))
        self.label_56.setText(_translate("SEMEA", "Latitude"))
        self.label_57.setText(_translate("SEMEA", "Longitude:"))
        self.groupBox_7.setTitle(_translate("SEMEA", "FERTILIZER"))
        self.label_50.setText(_translate("SEMEA", " Duty Cicle (%):"))
        self.label_51.setText(_translate("SEMEA", "Mass (kg/s):"))
        self.save_cal_fert.setText(_translate("SEMEA", "SAVE POINT"))
        self.cal_fert.setText(_translate("SEMEA", "CALIBRATE"))
        self.groupBox_6.setTitle(_translate("SEMEA", "SEEDER"))
        self.label_52.setText(_translate("SEMEA", "Duty Cicle (%):"))
        self.label_53.setText(_translate("SEMEA", "Speed (hz):"))
        self.save_cal_seed.setText(_translate("SEMEA", "SAVE POINT"))
        self.cal_seed.setText(_translate("SEMEA", "CALIBRATE"))
        SEMEA.setTabText(SEMEA.indexOf(self.aux), _translate("SEMEA", "  CALIBATION"))

from ClickableLineEdit import ClickableLineEdit

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SEMEA = QtWidgets.QTabWidget()
    ui = Ui_SEMEA()
    ui.setupUi(SEMEA)
    SEMEA.show()
    sys.exit(app.exec_())

